# Generated by Django 3.1.4 on 2021-03-22 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling', '0002_auto_20210315_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='canceled_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments_canceled_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Canceled By'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='filed_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments_filed_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Filed By'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='scheduled_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments_scheduled_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Scheduled By'),
        ),
        migrations.AlterField(
            model_name='appointmentstate',
            name='state_code',
            field=models.IntegerField(choices=[(0, 'Scheduled'), (1, 'Filed'), (2, 'Canceled'), (3, 'Absent')], verbose_name='State code'),
        ),
    ]
