# Generated by Django 3.1.4 on 2021-04-08 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0014_auto_20210408_1548'),
        ('scheduling', '0005_auto_20210324_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='treating_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clinic.treatingdoctor', verbose_name='Treating Doctor'),
        ),
    ]
