# Generated by Django 3.1.4 on 2021-07-14 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_appointment_treating_doctor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointmentstateuserlog',
            unique_together=set(),
        ),
    ]
