# Generated by Django 3.1.4 on 2022-06-07 14:38

from django.db import migrations, models
import django.db.models.deletion
import scheduling.models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_auto_20210714_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentDocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Appointment Document Type',
                'verbose_name_plural': 'Appointment Document Types',
            },
        ),
        migrations.CreateModel(
            name='AppointmentDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('file', models.FileField(upload_to=scheduling.models.appointment_document_storage_path, verbose_name='File')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_documents', to='scheduling.appointment', verbose_name='Appointment')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_documents', to='scheduling.appointmentdocumenttype', verbose_name='Document Type')),
            ],
            options={
                'verbose_name': 'Appointment Document',
                'verbose_name_plural': 'Appointment Documents',
            },
        ),
    ]
