# Generated by Django 3.1.4 on 2023-09-14 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_appointmentdocument_appointmentdocumenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='contact_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Contact Email'),
        ),
    ]
