# Generated by Django 3.1.4 on 2023-10-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_auto_20230913_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact Email'),
        ),
    ]
