version: "3"

services:
  db:
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432"
    env_file:
      - ./.env.dev
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: gunicorn --bind 0.0.0.0:8000 --workers 3 sistema.wsgi
    restart: always
    volumes:
      - media_volume:/code/media/
      - static_volume:/code/staticfiles/

    ports:
      - 8001:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

    networks:
      - default
      - nginx-proxy_smartapps

  sifen:
    depends_on:
      - web
    image: registry.gitlab.com/bellbird1/bellbird/sifen:latest
    ports:
      - 3000:3000
    env_file:
      - ./.env.dev
    volumes:
      - sifen_data:/src/certificados_clientes/
    command: npm run start
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume:
  sifen_data:

networks:
  nginx-proxy_smartapps:
    external: true