version: "3"

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "15432:5432"
    env_file:
      - ./.env.prod
    restart: always
  web:
    image: registry.gitlab.com/bellbird1/iribas/sistema:1.0.4
    command: gunicorn --bind 0.0.0.0:8000 --workers 3 sistema.wsgi
    restart: always
    volumes:
      - media_volume:/code/media/
      - static_volume:/code/staticfiles/
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  sifen:
    depends_on:
      - web
    image: registry.gitlab.com/bellbird1/bellbird/sifen:latest
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - ./.env.prod
    volumes:
      - sifen_data:/src/certificados_clientes/
    command: npm run start

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - media_volume:/code/media/
      - static_volume:/code/staticfiles/

    ports:
      - '80:80'
    depends_on:
      - web

  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - /root/backups:/backups
    links:
      - db
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=iribas
      - POSTGRES_USER=iribas
      - POSTGRES_PASSWORD=iribas2020Staging2020.,


volumes:
  postgres_data:
  static_volume:
  media_volume:
  sifen_data:

