# Generated by Django 3.1.4 on 2021-03-13 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalstudy',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='base.currency', verbose_name='Currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalstudy',
            name='price',
            field=models.FloatField(default=1000000, verbose_name='Price'),
            preserve_default=False,
        ),
    ]
