# Generated by Django 3.1.4 on 2021-03-15 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_auto_20210313_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalequipmenttype',
            name='equipment_type_code',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='equipment_type_code'),
        ),
    ]
