# Generated by Django 3.1.4 on 2021-03-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_medicalequipmenttype_equipment_type_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalequipmenttype',
            name='equipment_type_code',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Equipment Type Code'),
        ),
    ]
