# Generated by Django 3.1.4 on 2021-03-17 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        ('clinic', '0005_medicalstudyinsuranceagreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalSupplyInsuranceAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('coverage_percentage', models.IntegerField(default=0, verbose_name='Coverage Percentage')),
                ('insurance_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_supply_insurance_agreements', to='clinic.insuranceplan', verbose_name='Insurance Plan')),
                ('medical_supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_supply_insurance_agreements', to='stock.product', verbose_name='Medical Supply')),
            ],
            options={
                'verbose_name': 'Medical Supply Insurance Agreement',
                'verbose_name_plural': 'Medical Supplies Insurances Agreements',
            },
        ),
    ]
