# Generated by Django 3.1.4 on 2021-03-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_medicalsupplyinsuranceagreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalstudyinsuranceagreement',
            name='coverage_percentage',
            field=models.FloatField(default=0, verbose_name='Coverage Percentage'),
        ),
        migrations.AlterField(
            model_name='medicalsupplyinsuranceagreement',
            name='coverage_percentage',
            field=models.FloatField(default=0, verbose_name='Coverage Percentage'),
        ),
    ]
