# Generated by Django 3.1.4 on 2021-04-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_auto_20210330_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='sex',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0, verbose_name='Sex'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0, verbose_name='Sex'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technician',
            name='sex',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0, verbose_name='Sex'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatingdoctor',
            name='sex',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0, verbose_name='Sex'),
            preserve_default=False,
        ),
    ]
