# Generated by Django 3.1.4 on 2021-04-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0014_auto_20210408_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='sector',
        ),
        migrations.AddField(
            model_name='doctor',
            name='sector',
            field=models.ManyToManyField(related_name='doctors', to='clinic.Sector', verbose_name='Sector'),
        ),
    ]
