# Generated by Django 3.1.4 on 2021-04-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0016_auto_20210414_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_specializations',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='clinic.DoctorSpecialization', verbose_name='Specialization'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='sectors',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='clinic.Sector', verbose_name='Sectors'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='technician_specializations',
            field=models.ManyToManyField(blank=True, related_name='technicians', to='clinic.TechnicianSpecialization', verbose_name='Specializations'),
        ),
        migrations.AlterField(
            model_name='treatingdoctor',
            name='doctor_specializations',
            field=models.ManyToManyField(blank=True, related_name='treating_doctors', to='clinic.DoctorSpecialization', verbose_name='Specializations'),
        ),
    ]
