# Generated by Django 3.1.4 on 2021-04-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0017_auto_20210414_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='sectors',
            field=models.ManyToManyField(blank=True, related_name='technicians', to='clinic.Sector', verbose_name='Sectors'),
        ),
    ]
