# Generated by Django 3.1.4 on 2021-04-14 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0018_technician_sectors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalstudy',
            name='equipment_type_used',
        ),
    ]
