# Generated by Django 3.1.4 on 2021-04-14 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0019_remove_medicalstudy_equipment_type_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalequipment',
            name='type',
        ),
    ]
