# Generated by Django 3.1.4 on 2021-04-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0020_remove_medicalequipment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecompany',
            name='tax_identification_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Tax Identification Number'),
        ),
    ]
