# Generated by Django 3.1.4 on 2021-04-23 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        ('base', '0001_initial'),
        ('clinic', '0021_insurancecompany_tax_identification_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePlanMedicalSupplyFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('price', models.FloatField(verbose_name='Price')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.currency', verbose_name='Currency')),
                ('insurance_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insurance_plan_medical_supply_fees', to='clinic.insuranceplan', verbose_name='Insurance Plan')),
                ('medical_supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insurance_plan_medical_supply_fees', to='stock.product', verbose_name='Medical Supply')),
            ],
            options={
                'verbose_name': 'Insurance Plan Medical Supply Fee',
                'verbose_name_plural': 'Insurance Plan Medical Supplies Fees',
            },
        ),
    ]
