# Generated by Django 3.1.4 on 2021-08-10 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinic', '0023_auto_20210517_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
