# Generated by Django 3.1.4 on 2021-08-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0025_auto_20210810_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='usuario',
            new_name='user',
        ),
        migrations.AddField(
            model_name='doctor',
            name='digital_signature',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Digital Signature'),
        ),
    ]
