# Generated by Django 3.1.4 on 2023-09-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0029_auto_20230908_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='address',
            field=models.CharField(max_length=150, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='tax_identification_name',
            field=models.CharField(max_length=15, null=True, verbose_name='Tax Identification Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(max_length=150, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tax_identification_name',
            field=models.CharField(max_length=15, null=True, verbose_name='Tax Identification Name'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='address',
            field=models.CharField(max_length=150, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='phone_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='tax_identification_name',
            field=models.CharField(max_length=15, null=True, verbose_name='Tax Identification Name'),
        ),
        migrations.AlterField(
            model_name='treatingdoctor',
            name='address',
            field=models.CharField(max_length=150, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='treatingdoctor',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='treatingdoctor',
            name='phone_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='treatingdoctor',
            name='tax_identification_name',
            field=models.CharField(max_length=15, null=True, verbose_name='Tax Identification Name'),
        ),
    ]
