# Generated by Django 3.1.4 on 2023-09-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0030_auto_20230913_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='tax_identification_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Tax Identification Name'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='tax_identification_number',
            field=models.CharField(max_length=15, null=True, verbose_name='Tax Identification Number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tax_identification_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Tax Identification Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tax_identification_number',
            field=models.CharField(max_length=15, null=True, verbose_name='Tax Identification Number'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='tax_identification_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Tax Identification Name'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='tax_identification_number',
            field=models.CharField(max_length=15, null=True, verbose_name='Tax Identification Number'),
        ),
        migrations.AlterField(
            model_name='treatingdoctor',
            name='tax_identification_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Tax Identification Name'),
        ),
        migrations.AlterField(
            model_name='treatingdoctor',
            name='tax_identification_number',
            field=models.CharField(max_length=15, null=True, verbose_name='Tax Identification Number'),
        ),
    ]
