# Generated by Django 3.1.4 on 2023-09-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0031_auto_20230913_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_taxpayer',
            field=models.BooleanField(default=True, null=True, verbose_name='Is Taxpayer'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_taxpayer',
            field=models.BooleanField(default=True, null=True, verbose_name='Is Taxpayer'),
        ),
        migrations.AddField(
            model_name='technician',
            name='is_taxpayer',
            field=models.BooleanField(default=True, null=True, verbose_name='Is Taxpayer'),
        ),
        migrations.AddField(
            model_name='treatingdoctor',
            name='is_taxpayer',
            field=models.BooleanField(default=True, null=True, verbose_name='Is Taxpayer'),
        ),
    ]
