# Generated by Django 3.1.4 on 2021-06-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_definition', models.TextField()),
                ('report_type', models.CharField(max_length=30)),
                ('remark', models.TextField(null=True)),
                ('last_modified_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Report Definition',
                'verbose_name_plural': 'Reports Definitions',
            },
        ),
        migrations.CreateModel(
            name='ReportRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=36)),
                ('report_definition', models.TextField()),
                ('data', models.TextField()),
                ('is_test_data', models.BooleanField()),
                ('pdf_file', models.BinaryField(null=True)),
                ('pdf_file_size', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Report Request',
                'verbose_name_plural': 'Reports Requests',
            },
        ),
    ]
