# Generated by Django 3.1.4 on 2021-06-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Abbreviation'),
        ),
    ]
