# Generated by Django 3.1.4 on 2021-11-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_paymentmethod_abbreviation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedetails',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='invoicedetails',
            name='total_price',
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='exempt',
            field=models.FloatField(blank=True, null=True, verbose_name='EXENTAS'),
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='tax_10',
            field=models.FloatField(blank=True, null=True, verbose_name='IVA 10%'),
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='tax_5',
            field=models.FloatField(blank=True, null=True, verbose_name='IVA 5%'),
        ),
        migrations.AddField(
            model_name='invoiceheader',
            name='subtotal',
            field=models.FloatField(default=0.0, verbose_name='Subtotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceheader',
            name='total_tax',
            field=models.FloatField(blank=True, null=True, verbose_name='TOTAL IMPUESTOS'),
        ),
        migrations.AddField(
            model_name='invoiceheader',
            name='total_tax10',
            field=models.FloatField(blank=True, null=True, verbose_name='IVA 10%'),
        ),
        migrations.AddField(
            model_name='invoiceheader',
            name='total_tax5',
            field=models.FloatField(blank=True, null=True, verbose_name='IVA 5%'),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='payment_term',
            field=models.CharField(choices=[('CONTADO', 'CONTADO'), ('CREDITO', 'CREDITO')], max_length=15, verbose_name='Condicion de pago'),
        ),
    ]
