# Generated by Django 3.1.4 on 2021-11-23 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_auto_20211123_1412'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentTerm',
        ),
    ]
