# Generated by Django 3.1.4 on 2021-11-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_auto_20211124_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceheader',
            name='total_exempt',
            field=models.FloatField(blank=True, null=True, verbose_name='TOTAL EXEMPTS'),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='exempt',
            field=models.FloatField(blank=True, null=True, verbose_name='EXEMPTS'),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='tax_10',
            field=models.FloatField(blank=True, null=True, verbose_name='TAX 10%'),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='tax_5',
            field=models.FloatField(blank=True, null=True, verbose_name='TAX 5%'),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='invoice_number',
            field=models.CharField(max_length=25, unique=True, verbose_name='Invoice Number'),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='total_tax',
            field=models.FloatField(blank=True, null=True, verbose_name='TOTAL TAXES'),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='total_tax10',
            field=models.FloatField(blank=True, null=True, verbose_name='TOTAL TAX 10%'),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='total_tax5',
            field=models.FloatField(blank=True, null=True, verbose_name='TOTAL TAX 5%'),
        ),
    ]
