# Generated by Django 3.1.4 on 2021-11-30 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoicing', '0009_auto_20211130_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='stamprange',
            name='user',
            field=models.ForeignKey(default=37, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
    ]
