# Generated by Django 3.1.4 on 2021-12-04 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0010_stamprange_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuingCompanyName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company_name', models.CharField(max_length=40, unique=True, verbose_name='Company Name')),
                ('company_tax_id', models.CharField(max_length=50, unique=True, verbose_name='Client Tax Identification Number')),
                ('stamp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company', to='invoicing.invoicestamp', verbose_name='Invoice Stamp')),
            ],
            options={
                'permissions': (('can_undelete', 'Can undelete this object'),),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='invoiceheader',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='invoicing.issuingcompanyname'),
        ),
    ]
