# Generated by Django 3.1.4 on 2021-12-04 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0011_auto_20211204_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuingcompanyname',
            name='stamp',
        ),
        migrations.AddField(
            model_name='invoicestamp',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='invoicing.issuingcompanyname', verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='invoicing.issuingcompanyname', verbose_name='Company Name'),
        ),
    ]
