# Generated by Django 3.1.4 on 2021-12-06 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0012_auto_20211204_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceheader',
            name='invoice_range',
        ),
        migrations.AddField(
            model_name='invoiceheader',
            name='invoice_stamp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='invoicing.invoicestamp'),
        ),
        migrations.AlterField(
            model_name='invoicestamp',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company', to='invoicing.issuingcompanyname', verbose_name='Company Name'),
        ),
    ]
