# Generated by Django 3.1.4 on 2021-12-06 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0013_auto_20211206_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceheader',
            name='invoice_stamp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoicing.invoicestamp'),
        ),
    ]
