# Generated by Django 3.1.4 on 2021-12-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0015_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceheader',
            name='invoice_number',
            field=models.CharField(max_length=25, verbose_name='Invoice Number'),
        ),
    ]
