# Generated by Django 3.1.4 on 2021-12-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0018_auto_20211214_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='invoicestamp',
            options={'verbose_name': 'Invoice Stamp', 'verbose_name_plural': 'Invoice Stamps'},
        ),
        migrations.AlterModelOptions(
            name='issuingcompanyname',
            options={'verbose_name': 'Company Name', 'verbose_name_plural': 'Company Name'},
        ),
        migrations.AlterModelOptions(
            name='stamprange',
            options={'verbose_name': 'StampRange', 'verbose_name_plural': 'StampRange'},
        ),
        migrations.AddField(
            model_name='invoiceheader',
            name='total_exempt',
            field=models.FloatField(blank=True, null=True, verbose_name='TOTAL EXEMPTS'),
        ),
    ]
