# Generated by Django 3.1.4 on 2021-12-14 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0018_auto_20211214_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'Payment Method', 'verbose_name_plural': 'Payment Methods'},
        ),
    ]
