# Generated by Django 3.1.4 on 2021-12-14 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0019_auto_20211214_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicerange',
            options={'verbose_name': 'Invoice Range', 'verbose_name_plural': 'Invoice Ranges'},
        ),
    ]
