# Generated by Django 3.1.4 on 2022-01-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0020_auto_20211214_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(default='Cliente generado para no ser nulo', max_length=40, verbose_name='Customer Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_tax_id_number',
            field=models.CharField(default='1234567-8', max_length=40, unique=True, verbose_name='Customer Tax Identification Number'),
            preserve_default=False,
        ),
    ]
