# Generated by Django 3.1.4 on 2021-12-21 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0019_auto_20211214_1728'),
        ('invoicing', '0020_auto_20211214_1741'),
    ]

    operations = [
    ]
