# Generated by Django 3.1.4 on 2021-12-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0021_merge_20211221_1016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuingcompanyname',
            options={'verbose_name': 'Company Name', 'verbose_name_plural': 'Company Names'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'Payment Method', 'verbose_name_plural': 'Payment Method'},
        ),
        migrations.AlterModelOptions(
            name='stamprange',
            options={'verbose_name': 'StampRange', 'verbose_name_plural': 'StampRange'},
        ),
        migrations.AddField(
            model_name='invoiceheader',
            name='total_exempt',
            field=models.FloatField(blank=True, null=True, verbose_name='TOTAL EXEMPTS'),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='invoice_date',
            field=models.DateField(verbose_name='Invoice Date'),
        ),
    ]
