# Generated by Django 3.1.4 on 2022-01-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0021_auto_20220124_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicestamp',
            name='endDate',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='invoicestamp',
            name='number',
            field=models.CharField(max_length=30, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='invoicestamp',
            name='startDate',
            field=models.DateField(verbose_name='Start Date'),
        ),
    ]
