# Generated by Django 3.1.4 on 2022-01-25 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoicing', '0022_auto_20220124_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stamprange',
            options={'verbose_name': 'Stamp Range', 'verbose_name_plural': 'Stamp Ranges'},
        ),
        migrations.AlterField(
            model_name='invoicerange',
            name='boca_number',
            field=models.CharField(max_length=30, verbose_name='Collection Point Number'),
        ),
        migrations.AlterField(
            model_name='invoicerange',
            name='end_number',
            field=models.CharField(max_length=30, verbose_name='End Number'),
        ),
        migrations.AlterField(
            model_name='invoicerange',
            name='start_number',
            field=models.CharField(max_length=30, verbose_name='Start Number'),
        ),
        migrations.AlterField(
            model_name='invoicerange',
            name='sucursal_number',
            field=models.CharField(max_length=30, verbose_name='Branch Office Number'),
        ),
        migrations.AlterField(
            model_name='stamprange',
            name='range_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoicing.invoicerange', verbose_name='Invoice Range'),
        ),
        migrations.AlterField(
            model_name='stamprange',
            name='stamp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoicing.invoicestamp', verbose_name='Stamp'),
        ),
        migrations.AlterField(
            model_name='stamprange',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
