# Generated by Django 3.1.4 on 2021-12-21 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0022_auto_20211221_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stamprange',
            options={'verbose_name': 'Stamp Range', 'verbose_name_plural': 'Stamp Ranges'},
        ),
    ]
