# Generated by Django 3.1.4 on 2022-01-25 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0023_auto_20220125_0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuingcompanyname',
            options={'verbose_name': 'Issuing Company Name', 'verbose_name_plural': 'Issuing Company Name'},
        ),
    ]
