# Generated by Django 3.1.4 on 2022-01-25 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0025_auto_20220125_0005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuingcompanyname',
            options={'verbose_name': 'Issuing Company', 'verbose_name_plural': 'Issuing Company'},
        ),
    ]
