# Generated by Django 3.1.4 on 2022-01-25 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0026_auto_20220125_0006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuingcompanyname',
            options={'verbose_name': 'Issuing Company', 'verbose_name_plural': 'Issuing Companys'},
        ),
    ]
