# Generated by Django 3.1.4 on 2022-02-17 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0027_auto_20220125_0007'),
        ('invoicing', '0024_auto_20220112_2241'),
    ]

    operations = [
    ]
