# Generated by Django 3.1.4 on 2022-03-16 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0028_merge_20220217_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuingcompanyname',
            options={'verbose_name': 'Issuing Company', 'verbose_name_plural': 'Issuing Companys'},
        ),
        migrations.AlterModelOptions(
            name='stamprange',
            options={'verbose_name': 'Stamp Range', 'verbose_name_plural': 'Stamp Ranges'},
        ),
    ]
