# Generated by Django 3.1.4 on 2023-03-24 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0029_auto_20220315_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceheader',
            name='invoice_cdc',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Invoice CDC'),
        ),
    ]
