# Generated by Django 3.1.4 on 2023-03-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0030_invoiceheader_invoice_cdc'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceheader',
            name='invoice_pdf_base64',
            field=models.TextField(blank=True, null=True, verbose_name='Invoice PDF base64'),
        ),
        migrations.AddField(
            model_name='invoiceheader',
            name='invoice_xml_text',
            field=models.TextField(blank=True, null=True, verbose_name='Invoice XML'),
        ),
    ]
