# Generated by Django 3.1.4 on 2023-03-24 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoicing', '0031_auto_20230324_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='SifenTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('transaction_datetime', models.DateTimeField(auto_now=True, verbose_name='Transaction Date Time')),
                ('payload', models.JSONField(verbose_name='Payload')),
                ('response', models.JSONField(verbose_name='Response')),
                ('success', models.BooleanField(default=False, verbose_name='Success')),
                ('invoice_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sifen_transactions', to='invoicing.invoiceheader', verbose_name='Invoice Header')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Sifen Transaction',
                'verbose_name_plural': 'Sifen Transactions',
            },
        ),
    ]
