# Generated by Django 3.1.4 on 2023-03-27 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0032_sifentransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sifentransaction',
            name='invoice_header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sifen_transactions', to='invoicing.invoiceheader', verbose_name='Invoice Header'),
        ),
        migrations.AlterField(
            model_name='sifentransaction',
            name='payload',
            field=models.JSONField(blank=True, null=True, verbose_name='Payload'),
        ),
        migrations.AlterField(
            model_name='sifentransaction',
            name='response',
            field=models.JSONField(blank=True, null=True, verbose_name='Response'),
        ),
    ]
