# Generated by Django 3.1.4 on 2023-03-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0033_auto_20230327_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceheader',
            name='invoice_cdc',
            field=models.CharField(blank=True, max_length=44, null=True, verbose_name='Invoice CDC'),
        ),
    ]
