# Generated by Django 3.1.4 on 2023-03-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0034_auto_20230329_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_email',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Customer Email'),
        ),
    ]
