# Generated by Django 3.1.4 on 2023-03-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0035_customer_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceheader',
            name='client_email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Client Email'),
        ),
    ]
