# Generated by Django 3.1.4 on 2023-03-29 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0039_auto_20230329_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceheader',
            old_name='invoice_email_sended',
            new_name='invoice_email_sent',
        ),
    ]
