# Generated by Django 3.1.4 on 2023-05-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0040_auto_20230329_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceheader',
            name='invoice_cdc',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Invoice CDC'),
        ),
    ]
