# Generated by Django 3.1.4 on 2023-06-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0041_auto_20230524_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuingcompanyname',
            name='sifen_business_name',
            field=models.CharField(max_length=200, null=True, verbose_name='SIFEN BUSINESS NAME'),
        ),
        migrations.AddField(
            model_name='issuingcompanyname',
            name='sifen_digital_signature_date',
            field=models.CharField(max_length=100, null=True, verbose_name='SIFEN DIGITAL SIGNATURE DATE'),
        ),
        migrations.AddField(
            model_name='issuingcompanyname',
            name='sifen_economic_activity_code',
            field=models.CharField(max_length=4, null=True, verbose_name='SIFEN ECONOMIC ACTIVITY CODE'),
        ),
        migrations.AddField(
            model_name='issuingcompanyname',
            name='sifen_economic_activity_description',
            field=models.CharField(max_length=200, null=True, verbose_name='SIFEN ECONOMIC ACTIVITY DESCRIPTION'),
        ),
        migrations.AddField(
            model_name='issuingcompanyname',
            name='sifen_email_default_from',
            field=models.CharField(max_length=200, null=True, verbose_name='SIFEN EMAIL DEFAULT FROM'),
        ),
        migrations.AddField(
            model_name='issuingcompanyname',
            name='sifen_email_host',
            field=models.CharField(max_length=100, null=True, verbose_name='SIFEN EMAIL HOST'),
        ),
        migrations.AddField(
            model_name='issuingcompanyname',
            name='sifen_email_host_password',
            field=models.CharField(max_length=100, null=True, verbose_name='SIFEN EMAIL HOST PASSWORD'),
        ),
        migrations.AddField(
            model_name='issuingcompanyname',
            name='sifen_email_host_user',
            field=models.CharField(max_length=100, null=True, verbose_name='SIFEN EMAIL HOST USER'),
        ),
        migrations.AddField(
            model_name='issuingcompanyname',
            name='sifen_email_port',
            field=models.CharField(max_length=5, null=True, verbose_name='SIFEN EMAIL PORT'),
        ),
        migrations.AddField(
            model_name='issuingcompanyname',
            name='sifen_email_use_tls',
            field=models.BooleanField(default=True, verbose_name='SIFEN EMAIL USE TLS'),
        ),
        migrations.AddField(
            model_name='issuingcompanyname',
            name='sifen_establishment_city_code',
            field=models.CharField(max_length=3, null=True, verbose_name='SIFEN ESTABLISHMENT CITY CODE'),
        ),
        migrations.AddField(
            model_name='issuingcompanyname',
            name='sifen_establishment_city_description',
            field=models.CharField(max_length=50, null=True, verbose_name='SIFEN ESTABLISHMENT DISTRICT DESCRIPTION'),
        ),
        migrations.AddField(
            model_name='issuingcompanyname',
            name='sifen_establishment_code',
            field=models.CharField(max_length=4, null=True, verbose_name='SIFEN ESTABLISHMENT CODE'),
        ),
        migrations.AddField(
            model_name='issuingcompanyname',
            name='sifen_establishment_denomination',
            field=models.CharField(max_length=200, null=True, verbose_name='SIFEN ESTABLISHMENT DENOMINATION'),
        ),
        migrations.AddField(
            model_name='issuingcompanyname',
            name='sifen_establishment_department_code',
            field=models.CharField(max_length=3, null=True, verbose_name='SIFEN ESTABLISHMENT DEPARTMENT CODE'),
        ),
        migrations.AddField(
            model_name='issuingcompanyname',
            name='sifen_establishment_department_description',
            field=models.CharField(max_length=200, null=True, verbose_name='SIFEN ESTABLISHMENT DEPARTMENT DESCRIPTION'),
        ),
        migrations.AddField(
            model_name='issuingcompanyname',
            name='sifen_establishment_direction',
            field=models.CharField(max_length=200, null=True, verbose_name='SIFEN ESTABLISHMENT DIRECTION'),
        ),
        migrations.AddField(
            model_name='issuingcompanyname',
            name='sifen_establishment_district_code',
            field=models.CharField(max_length=3, null=True, verbose_name='SIFEN ESTABLISHMENT DISTRICT CODE'),
        ),
        migrations.AddField(
            model_name='issuingcompanyname',
            name='sifen_establishment_district_description',
            field=models.CharField(max_length=200, null=True, verbose_name='SIFEN ESTABLISHMENT DISTRICT DESCRIPTION'),
        ),
        migrations.AddField(
            model_name='issuingcompanyname',
            name='sifen_establishment_email',
            field=models.CharField(max_length=100, null=True, verbose_name='SIFEN ESTABLISHMENT EMAIL'),
        ),
        migrations.AddField(
            model_name='issuingcompanyname',
            name='sifen_establishment_house_number',
            field=models.CharField(max_length=200, null=True, verbose_name='SIFEN ESTABLISHMENT HOUSE NUMBER'),
        ),
        migrations.AddField(
            model_name='issuingcompanyname',
            name='sifen_establishment_phone',
            field=models.CharField(max_length=12, null=True, verbose_name='SIFEN ESTABLISHMENT PHONE'),
        ),
        migrations.AddField(
            model_name='issuingcompanyname',
            name='sifen_establishment_street_name_1',
            field=models.CharField(max_length=200, null=True, verbose_name='SIFEN ESTABLISHMENT STREET NAME 1'),
        ),
        migrations.AddField(
            model_name='issuingcompanyname',
            name='sifen_establishment_street_name_2',
            field=models.CharField(max_length=200, null=True, verbose_name='SIFEN ESTABLISHMENT STREET NAME 2'),
        ),
        migrations.AddField(
            model_name='issuingcompanyname',
            name='sifen_fantasy_name',
            field=models.CharField(max_length=200, null=True, verbose_name='SIFEN FANTASY NAME'),
        ),
        migrations.AddField(
            model_name='issuingcompanyname',
            name='sifen_id_csc',
            field=models.CharField(max_length=100, null=True, verbose_name='SIFEN ID CSC'),
        ),
        migrations.AddField(
            model_name='issuingcompanyname',
            name='sifen_logo',
            field=models.CharField(max_length=200, null=True, verbose_name='SIFEN LOGO'),
        ),
        migrations.AddField(
            model_name='issuingcompanyname',
            name='sifen_password',
            field=models.CharField(max_length=100, null=True, verbose_name='SIFEN PASSWORD'),
        ),
        migrations.AddField(
            model_name='issuingcompanyname',
            name='sifen_ruc',
            field=models.CharField(max_length=100, null=True, verbose_name='SIFEN RUC'),
        ),
        migrations.AddField(
            model_name='issuingcompanyname',
            name='sifen_stamp_date',
            field=models.CharField(max_length=100, null=True, verbose_name='SIFEN STAMP DATE'),
        ),
        migrations.AddField(
            model_name='issuingcompanyname',
            name='sifen_stamp_number',
            field=models.CharField(max_length=200, null=True, verbose_name='SIFEN STAMP NUMBER'),
        ),
    ]
