# Generated by Django 3.1.4 on 2023-06-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0042_auto_20230626_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuingcompanyname',
            name='sifen_csc',
            field=models.CharField(max_length=200, null=True, verbose_name='SIFEN CSC'),
        ),
    ]
