# Generated by Django 3.1.4 on 2023-06-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0043_issuingcompanyname_sifen_csc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuingcompanyname',
            name='sifen_establishment_city_description',
            field=models.CharField(max_length=50, null=True, verbose_name='SIFEN ESTABLISHMENT CITY DESCRIPTION'),
        ),
    ]
