# Generated by Django 3.1.4 on 2023-06-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0044_auto_20230628_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuingcompanyname',
            name='sifen_economic_activity_code',
            field=models.CharField(max_length=5, null=True, verbose_name='SIFEN ECONOMIC ACTIVITY CODE'),
        ),
    ]
