# Generated by Django 3.1.4 on 2023-08-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0045_auto_20230630_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicestamp',
            name='electronic_stamp',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
