# Generated by Django 3.1.4 on 2023-08-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0046_invoicestamp_electronic_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicestamp',
            name='electronic_stamp',
            field=models.BooleanField(default=False),
        ),
    ]
