# Generated by Django 3.1.4 on 2023-08-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0049_invoiceheader_invoice_batch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceheader',
            name='invoice_batch_sended',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Invoice Batch sended'),
        ),
    ]
