# Generated by Django 3.1.4 on 2023-08-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0050_invoiceheader_invoice_batch_sended'),
    ]

    operations = [
        migrations.AddField(
            model_name='sifentransaction',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
