# Generated by Django 3.1.4 on 2023-08-24 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220124_2329'),
        ('invoicing', '0051_sifentransaction_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceheader',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_headers', to='invoicing.issuingcompanyname', verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='invoice_stamp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_headers', to='invoicing.invoicestamp', verbose_name='Invoice Stamp'),
        ),
        migrations.CreateModel(
            name='CreditNoteStamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('startDate', models.DateField(verbose_name='Start Date')),
                ('endDate', models.DateField(verbose_name='End Date')),
                ('number', models.CharField(max_length=30, verbose_name='Number')),
                ('electronic_stamp', models.BooleanField(default=False)),
                ('company_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_note_stamps', to='invoicing.issuingcompanyname', verbose_name='Company Name')),
            ],
            options={
                'verbose_name': 'Credit Note Stamp',
                'verbose_name_plural': 'Credit Note Stamps',
            },
        ),
        migrations.CreateModel(
            name='CreditNoteHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('credit_note_number', models.CharField(max_length=25, verbose_name='Credit Note Number')),
                ('client_name', models.CharField(max_length=150, verbose_name='Client Name')),
                ('client_tax_identification_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Client Tax Identification Number')),
                ('client_email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Client Email')),
                ('credit_note_date', models.DateField(verbose_name='Credit note Date')),
                ('subtotal', models.FloatField(verbose_name='Subtotal')),
                ('invoice_total', models.FloatField(verbose_name='Invoice Total')),
                ('total_tax10', models.FloatField(blank=True, null=True, verbose_name='TOTAL TAX 10%')),
                ('total_tax5', models.FloatField(blank=True, null=True, verbose_name='TOTAL TAX 5%')),
                ('total_exempt', models.FloatField(blank=True, null=True, verbose_name='TOTAL EXEMPTS')),
                ('total_tax', models.FloatField(blank=True, null=True, verbose_name='TOTAL TAXES')),
                ('credit_note_total_letters', models.CharField(max_length=250, verbose_name='Credit Note Total Letters')),
                ('credit_note_cdc', models.CharField(blank=True, max_length=250, null=True, verbose_name='Credit Note CDC')),
                ('credit_note_xml_text', models.TextField(blank=True, null=True, verbose_name='Credit Note XML')),
                ('credit_note_pdf_base64', models.TextField(blank=True, null=True, verbose_name='Credit Note PDF base64')),
                ('credit_note_email_sent', models.BooleanField(default=False, null=True, verbose_name='Credit Note Sent')),
                ('credit_note_batch_id', models.CharField(blank=True, max_length=250, null=True, verbose_name='Credit Note Batch ID')),
                ('credit_note_batch_sended', models.BooleanField(blank=True, default=False, null=True, verbose_name='Credit Note Batch sended')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='invoicing.issuingcompanyname', verbose_name='Company Name')),
                ('credit_note_stamp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoicing.creditnotestamp', verbose_name='Credit Note Stamp')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='base.currency', verbose_name='Currency')),
                ('customer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='invoicing.customer', verbose_name='Customer')),
                ('invoice_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='invoicing.invoiceheader', verbose_name='Invoice Header')),
            ],
            options={
                'verbose_name': 'Credit Note Header',
                'verbose_name_plural': 'Credit Note Headers',
            },
        ),
        migrations.CreateModel(
            name='CreditNoteDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('unit_price', models.FloatField(verbose_name='Unit price')),
                ('tax_10', models.FloatField(blank=True, null=True, verbose_name='TAX 10%')),
                ('tax_5', models.FloatField(blank=True, null=True, verbose_name='TAX 5%')),
                ('exempt', models.FloatField(blank=True, null=True, verbose_name='EXEMPTS')),
                ('credit_note_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_note_details', to='invoicing.creditnoteheader', verbose_name='Credit Note Header')),
            ],
            options={
                'verbose_name': 'Credit Note Detail',
                'verbose_name_plural': 'Credit Note Details',
            },
        ),
    ]
