# Generated by Django 3.1.4 on 2023-08-30 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoicing', '0053_auto_20230824_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNoteRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('sucursal_number', models.CharField(max_length=30, verbose_name='Branch Office Number')),
                ('boca_number', models.CharField(max_length=30, verbose_name='Collection Point Number')),
                ('start_number', models.CharField(max_length=30, verbose_name='Start Number')),
                ('end_number', models.CharField(max_length=30, verbose_name='End Number')),
            ],
            options={
                'verbose_name': 'Credit Note Range',
                'verbose_name_plural': 'Credit Note Ranges',
            },
        ),
        migrations.CreateModel(
            name='CreditNoteStampRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('range_credit_note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoicing.creditnoterange', verbose_name='CreditNote Range')),
                ('stamp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoicing.creditnotestamp', verbose_name='Credit Note Stamp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Credit Note Stamp Range',
                'verbose_name_plural': 'Credit Note Stamp Ranges',
            },
        ),
    ]
