# Generated by Django 3.1.4 on 2023-09-03 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0054_creditnoterange_creditnotestamprange'),
    ]

    operations = [
        migrations.AddField(
            model_name='sifentransaction',
            name='credit_note_header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sifen_transactions', to='invoicing.creditnoteheader', verbose_name='Credit Note Header'),
        ),
    ]
