# Generated by Django 3.1.4 on 2023-09-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0055_sifentransaction_credit_note_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_address',
            field=models.CharField(max_length=250, null=True, verbose_name='Customer Address'),
        ),
    ]
