# Generated by Django 3.1.4 on 2023-09-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0056_customer_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceheader',
            name='client_address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Client Address'),
        ),
    ]
