# Generated by Django 3.1.4 on 2023-09-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0057_invoiceheader_client_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnoteheader',
            name='client_address',
            field=models.CharField(max_length=250, null=True, verbose_name='Client Address'),
        ),
    ]
