# Generated by Django 3.1.4 on 2023-09-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0058_creditnoteheader_client_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_phone_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Customer Phone Number'),
        ),
    ]
