# Generated by Django 3.1.4 on 2023-09-06 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0061_auto_20230905_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnotedetail',
            name='exempt',
            field=models.FloatField(default=0, null=True, verbose_name='EXEMPTS'),
        ),
        migrations.AlterField(
            model_name='creditnotedetail',
            name='tax_10',
            field=models.FloatField(default=0, null=True, verbose_name='TAX 10%'),
        ),
        migrations.AlterField(
            model_name='creditnotedetail',
            name='tax_5',
            field=models.FloatField(default=0, null=True, verbose_name='TAX 5%'),
        ),
        migrations.AlterField(
            model_name='creditnotedetail',
            name='unit_price',
            field=models.FloatField(default=0, verbose_name='Unit price'),
        ),
        migrations.AlterField(
            model_name='creditnoteheader',
            name='client_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Client Email'),
        ),
        migrations.AlterField(
            model_name='creditnoteheader',
            name='client_phone_number',
            field=models.CharField(max_length=15, null=True, verbose_name='Client Phone Number'),
        ),
        migrations.AlterField(
            model_name='creditnoteheader',
            name='client_tax_identification_number',
            field=models.CharField(max_length=50, null=True, verbose_name='Client Tax Identification Number'),
        ),
        migrations.AlterField(
            model_name='creditnoteheader',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='invoicing.issuingcompanyname', verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='creditnoteheader',
            name='subtotal',
            field=models.FloatField(default=0, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='creditnoteheader',
            name='total_exempt',
            field=models.FloatField(default=0, null=True, verbose_name='TOTAL EXEMPTS'),
        ),
        migrations.AlterField(
            model_name='creditnoteheader',
            name='total_tax',
            field=models.FloatField(default=0, null=True, verbose_name='TOTAL TAXES'),
        ),
        migrations.AlterField(
            model_name='creditnoteheader',
            name='total_tax10',
            field=models.FloatField(default=0, null=True, verbose_name='TOTAL TAX 10%'),
        ),
        migrations.AlterField(
            model_name='creditnoteheader',
            name='total_tax5',
            field=models.FloatField(default=0, null=True, verbose_name='TOTAL TAX 5%'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Customer Email'),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='exempt',
            field=models.FloatField(default=0, null=True, verbose_name='EXEMPTS'),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='tax_10',
            field=models.FloatField(default=0, null=True, verbose_name='TAX 10%'),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='tax_5',
            field=models.FloatField(default=0, null=True, verbose_name='TAX 5%'),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='unit_price',
            field=models.FloatField(default=0, verbose_name='Unit price'),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='client_address',
            field=models.CharField(max_length=250, null=True, verbose_name='Client Address'),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='client_email',
            field=models.CharField(max_length=200, null=True, verbose_name='Client Email'),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='client_phone_number',
            field=models.CharField(max_length=15, null=True, verbose_name='Client Phone Number'),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='client_tax_identification_number',
            field=models.CharField(max_length=50, null=True, verbose_name='Client Tax Identification Number'),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_headers', to='invoicing.issuingcompanyname', verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='subtotal',
            field=models.FloatField(default=0, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='total_exempt',
            field=models.FloatField(default=0, null=True, verbose_name='TOTAL EXEMPTS'),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='total_tax',
            field=models.FloatField(default=0, null=True, verbose_name='TOTAL TAXES'),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='total_tax10',
            field=models.FloatField(default=0, null=True, verbose_name='TOTAL TAX 10%'),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='total_tax5',
            field=models.FloatField(default=0, null=True, verbose_name='TOTAL TAX 5%'),
        ),
    ]
