# Generated by Django 3.1.4 on 2023-09-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0062_auto_20230906_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sifen_ruc_validated',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Sifen RUC Validated'),
        ),
    ]
