# Generated by Django 3.1.4 on 2023-09-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0063_customer_sifen_ruc_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='non_taxpayer',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Non Taxpayer'),
        ),
    ]
