# Generated by Django 3.1.4 on 2023-09-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0064_customer_non_taxpayer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='non_taxpayer',
        ),
        migrations.AddField(
            model_name='customer',
            name='is_taxpayer',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Is Taxpayer'),
        ),
    ]
