# Generated by Django 3.1.4 on 2023-09-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0066_customer_customer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_taxpayer',
            field=models.BooleanField(default=True, null=True, verbose_name='Is Taxpayer'),
        ),
    ]
