# Generated by Django 3.1.4 on 2023-09-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0067_auto_20230913_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.IntegerField(choices=[(0, 'Individual'), (1, 'Legal Entity')], default=0, null=True, verbose_name='Customer Type'),
        ),
    ]
