# Generated by Django 3.1.4 on 2021-10-20 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', 'custom_migration_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrintTagConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name_x', models.FloatField(verbose_name='Name X')),
                ('name_y', models.FloatField(verbose_name='Name Y')),
                ('last_name_x', models.FloatField(verbose_name='Last Name X')),
                ('last_name_y', models.FloatField(verbose_name='Last Name Y')),
                ('date_x', models.FloatField(verbose_name='Date X')),
                ('date_y', models.FloatField(verbose_name='Date Y')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_print_configuration', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'permissions': (('can_undelete', 'Can undelete this object'),),
                'abstract': False,
            },
        ),
    ]
