# Generated by Django 3.1.4 on 2021-10-20 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_userprinttagconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprinttagconfiguration',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user_print_configuration', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
