# Generated by Django 3.1.4 on 2022-01-25 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20211020_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprinttagconfiguration',
            options={'verbose_name': 'User Print Tag Configuration', 'verbose_name_plural': 'Users Print Tag Configurations'},
        ),
    ]
