# Generated by Django 3.1.4 on 2021-03-17 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_auto_20210316_0234'),
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationsheetdocument',
            name='document_name',
        ),
        migrations.AddField(
            model_name='consultationsheet',
            name='discount',
            field=models.FloatField(default=0, verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='consultationsheet',
            name='insurance_agreement_coverage_percent',
            field=models.IntegerField(default=0, verbose_name='Insurance Agreement Coverage Percent'),
        ),
        migrations.AddField(
            model_name='consultationsheet',
            name='medical_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultation_sheets', to='clinic.medicalequipment', verbose_name='Medical Equipment Used'),
        ),
        migrations.AddField(
            model_name='consultationsheet',
            name='medical_study_ammount_to_pay_insurance',
            field=models.FloatField(default=0, verbose_name='Medical Study Ammount to pay (Insurance)'),
        ),
        migrations.AddField(
            model_name='consultationsheet',
            name='medical_study_ammount_to_pay_patient',
            field=models.FloatField(default=0, verbose_name='Medical Study Ammount to pay (Patient)'),
        ),
        migrations.AddField(
            model_name='consultationsheet',
            name='medical_supplies_ammount_to_pay_insurance',
            field=models.FloatField(default=0, verbose_name='Medical Supplies Ammount to pay (Insurance)'),
        ),
        migrations.AddField(
            model_name='consultationsheet',
            name='medical_supplies_ammount_to_pay_patient',
            field=models.FloatField(default=0, verbose_name='Medical Supplies Ammount to pay (Patient)'),
        ),
        migrations.AddField(
            model_name='consultationsheet',
            name='reporting_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reporting_doctor_consultation_sheets', to='clinic.doctor', verbose_name='Doctor'),
        ),
        migrations.AddField(
            model_name='consultationsheet',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultation_sheets', to='clinic.technician', verbose_name='Technician'),
        ),
        migrations.AddField(
            model_name='consultationsheet',
            name='total_ammount_to_pay_insurance',
            field=models.FloatField(default=0, verbose_name='Total Amount to pay Insurance'),
        ),
        migrations.AddField(
            model_name='consultationsheet',
            name='total_ammount_to_pay_patient',
            field=models.FloatField(default=0, verbose_name='Total Amount to pay Patient'),
        ),
        migrations.AlterField(
            model_name='consultationsheet',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doctor_consultation_sheets', to='clinic.doctor', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='consultationsheet',
            name='treating_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treating_doctor_consultation_sheets', to='clinic.treatingdoctor', verbose_name='Treating Doctor'),
        ),
        migrations.CreateModel(
            name='MedicalStudyInsuranceAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('coverage_percentage', models.IntegerField(default=0, verbose_name='Coverage Percentage')),
                ('insurance_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_study_insurance_agreements', to='clinic.insuranceplan', verbose_name='Insurance Plan')),
                ('medical_study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_study_insurance_agreements', to='clinic.medicalstudy', verbose_name='Medical Study')),
            ],
            options={
                'verbose_name': 'Medical Study Insurance Agreement',
                'verbose_name_plural': 'Medical Studys Insurances Agreements',
            },
        ),
        migrations.AddField(
            model_name='consultationsheet',
            name='medical_study_insurance_agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultation_sheets', to='consultation.medicalstudyinsuranceagreement', verbose_name='Medical Study Insurance Agreement'),
        ),
    ]
