# Generated by Django 3.1.4 on 2021-03-17 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_medicalstudyinsuranceagreement'),
        ('consultation', '0002_auto_20210317_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationsheet',
            name='medical_study_insurance_agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultation_sheets', to='clinic.medicalstudyinsuranceagreement', verbose_name='Medical Study Insurance Agreement'),
        ),
        migrations.DeleteModel(
            name='MedicalStudyInsuranceAgreement',
        ),
    ]
