# Generated by Django 3.1.4 on 2021-03-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0004_auto_20210317_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalsupplyused',
            name='ammount_to_pay_insurance',
            field=models.FloatField(default=0, verbose_name='Ammount to Pay Insurance'),
        ),
        migrations.AddField(
            model_name='medicalsupplyused',
            name='ammount_to_pay_patient',
            field=models.FloatField(default=0, verbose_name='Ammount to Pay Patient'),
        ),
        migrations.AlterField(
            model_name='consultationsheet',
            name='insurance_agreement_coverage_percent',
            field=models.FloatField(default=0, verbose_name='Insurance Agreement Coverage Percent'),
        ),
    ]
