# Generated by Django 3.1.4 on 2021-03-17 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_auto_20210317_0329'),
        ('consultation', '0005_auto_20210317_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationsheet',
            name='reporting_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reporting_doctor_consultation_sheets', to='clinic.doctor', verbose_name='Reporting Doctor'),
        ),
    ]
