# Generated by Django 3.1.4 on 2021-03-18 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0007_auto_20210317_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationsheet',
            name='medical_study_insurance_agreement',
        ),
    ]
