# Generated by Django 3.1.4 on 2021-03-18 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0008_remove_consultationsheet_medical_study_insurance_agreement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalsupplyused',
            name='medical_supply_insurance_agreement',
        ),
    ]
