# Generated by Django 3.1.4 on 2021-03-22 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0009_remove_medicalsupplyused_medical_supply_insurance_agreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('state_code', models.IntegerField(choices=[(0, 'Filed'), (1, 'Performed'), (2, 'Assigned'), (3, 'Reported'), (4, 'Delivered')], verbose_name='State code')),
            ],
            options={
                'verbose_name': 'Consultation State',
                'verbose_name_plural': 'Consultation States',
            },
        ),
        migrations.AddField(
            model_name='consultationsheet',
            name='consultation_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultation_sheets', to='consultation.consultationstate', verbose_name='Consultation State'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='consultation_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consults', to='consultation.consultationstate', verbose_name='Consultation State'),
        ),
        migrations.DeleteModel(
            name='CosultationState',
        ),
    ]
