# Generated by Django 3.1.4 on 2021-03-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0010_auto_20210322_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationstate',
            name='state_code',
            field=models.IntegerField(choices=[(0, 'Filed'), (1, 'Performed'), (2, 'Assigned'), (3, 'Reported'), (4, 'Prepared'), (5, 'Delivered')], verbose_name='State code'),
        ),
    ]
