# Generated by Django 3.1.4 on 2021-03-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0012_auto_20210323_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationsheet',
            name='received_by',
            field=models.CharField(max_length=100, null=True, verbose_name='Received by (Name - and Document Number)'),
        ),
    ]
