# Generated by Django 3.1.4 on 2021-03-23 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
        ('consultation', '0014_auto_20210323_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationsheet',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultation_sheets', to='invoicing.paymentmethod', verbose_name='Payment Method'),
        ),
    ]
