# Generated by Django 3.1.4 on 2021-03-24 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultation', '0016_auto_20210323_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationsheet',
            name='delivered_by',
        ),
        migrations.RemoveField(
            model_name='consultationsheet',
            name='filed_by',
        ),
        migrations.RemoveField(
            model_name='consultationsheet',
            name='performed_by',
        ),
        migrations.RemoveField(
            model_name='consultationsheet',
            name='reported_by',
        ),
        migrations.CreateModel(
            name='ConsultationStateUserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('state_log_datetime', models.DateTimeField(auto_now=True, verbose_name='State log datetime')),
                ('consultation_sheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultation_states_user_logs', to='consultation.consultationsheet', verbose_name='Consultation Sheet')),
                ('consultation_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultation_states_user_logs', to='consultation.consultationstate', verbose_name='Consultation State')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultation_states_user_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Consultation State User Log',
                'verbose_name_plural': 'Consultations States User Logs',
            },
        ),
    ]
