# Generated by Django 3.1.4 on 2021-03-24 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0017_auto_20210324_1931'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consultationstateuserlog',
            unique_together={('consultation_sheet', 'consultation_state')},
        ),
    ]
