# Generated by Django 3.1.4 on 2021-03-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0018_auto_20210324_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationsheet',
            name='received_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Received by (Name - and Document Number)'),
        ),
    ]
