# Generated by Django 3.1.4 on 2021-03-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0019_auto_20210325_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationsheet',
            name='total_ammount_to_pay_patient_with_discount',
            field=models.FloatField(default=0, verbose_name='Total Amount to pay Patient with discount'),
        ),
    ]
