# Generated by Django 3.1.4 on 2021-04-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0020_consultationsheet_total_ammount_to_pay_patient_with_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationsheet',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observations'),
        ),
    ]
