# Generated by Django 3.1.4 on 2021-04-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0021_consultationsheet_observations'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationsheet',
            name='internal_results_delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Internal Results Delivery Date'),
        ),
        migrations.AddField(
            model_name='consultationsheet',
            name='patient_results_delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Patient Results Delivery Date'),
        ),
    ]
