# Generated by Django 3.1.4 on 2021-04-13 14:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0014_auto_20210408_1548'),
        ('consultation', '0022_auto_20210408_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationEntrySheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('consultation_entry_sheet_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Consultation Entry Sheet Date')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultation_entry_sheets', to='clinic.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Consultation Entry Sheet',
                'verbose_name_plural': 'Consultation Entry Sheets',
            },
        ),
        migrations.AddField(
            model_name='consultationsheet',
            name='consultation_entry_sheet',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultation_sheets', to='consultation.consultationentrysheet', verbose_name='Consultation Entry Sheet'),
        ),
    ]
