# Generated by Django 3.1.4 on 2021-05-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0023_auto_20210413_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalsupplyused',
            name='cover_type',
            field=models.FloatField(default=0, verbose_name='Cover Type'),
        ),
        migrations.AddField(
            model_name='medicalsupplyused',
            name='insurance_agreement_coverage_amount',
            field=models.FloatField(default=0, verbose_name='Insurance Agreement Coverage Amount'),
        ),
    ]
