# Generated by Django 3.1.4 on 2021-05-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0024_auto_20210517_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationsheet',
            name='insurance_agreement_coverage_amount',
            field=models.FloatField(default=0, verbose_name='Insurance Agreement Coverage Amount'),
        ),
        migrations.AddField(
            model_name='consultationsheet',
            name='study_cover_type',
            field=models.IntegerField(default=0, verbose_name='Study Cover Type'),
        ),
        migrations.AlterField(
            model_name='medicalsupplyused',
            name='cover_type',
            field=models.IntegerField(default=0, verbose_name='Cover Type'),
        ),
    ]
