# Generated by Django 3.1.4 on 2021-05-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0025_auto_20210519_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationsheet',
            name='study_cover_type',
            field=models.IntegerField(choices=[(0, 'Percentage'), (1, 'Amount')], default=0, verbose_name='Study Cover Type'),
        ),
        migrations.AlterField(
            model_name='medicalsupplyused',
            name='cover_type',
            field=models.IntegerField(choices=[(0, 'Percentage'), (1, 'Amount')], default=0, verbose_name='Cover Type'),
        ),
    ]
