# Generated by Django 3.1.4 on 2021-05-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0026_auto_20210521_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalsupplyused',
            name='total_price',
            field=models.FloatField(default=0, verbose_name='Total'),
        ),
    ]
