# Generated by Django 3.1.4 on 2021-05-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0027_medicalsupplyused_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationsheet',
            name='amount_paid',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Amount Paid'),
        ),
    ]
