# Generated by Django 3.1.4 on 2021-06-09 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('consultation', '0028_consultationsheet_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationentrysheet',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='consultation_entrey_sheets', to='base.currency', verbose_name='Currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultationentrysheet',
            name='patient_balance',
            field=models.FloatField(default=0, verbose_name='Patient Balance'),
        ),
        migrations.AddField(
            model_name='consultationentrysheet',
            name='total_amount',
            field=models.FloatField(default=0, verbose_name='Total amount'),
        ),
        migrations.AddField(
            model_name='consultationentrysheet',
            name='total_amount_to_pay_insurance',
            field=models.FloatField(default=0, verbose_name='Total amount to pay insurance'),
        ),
        migrations.AddField(
            model_name='consultationentrysheet',
            name='total_amount_to_pay_patient',
            field=models.FloatField(default=0, verbose_name='Total amount to pay patient'),
        ),
        migrations.AddField(
            model_name='consultationsheet',
            name='patient_balance',
            field=models.FloatField(default=0, verbose_name='Patient Balance'),
        ),
    ]
