# Generated by Django 3.1.4 on 2021-06-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0029_auto_20210609_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationentrysheet',
            name='total_amount_paid_by_patient',
            field=models.FloatField(default=0, verbose_name='Total amount Paid by Patient'),
        ),
    ]
