# Generated by Django 3.1.4 on 2021-07-14 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0030_consultationentrysheet_total_amount_paid_by_patient'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consultationstateuserlog',
            unique_together=set(),
        ),
    ]
