# Generated by Django 3.1.4 on 2021-08-09 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0031_auto_20210714_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='insurance_plan_cover_percentage',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='consultation',
            name='consultation_sheet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='consults', to='consultation.consultationsheet', verbose_name='Consultation Sheet'),
            preserve_default=False,
        ),
    ]
