# Generated by Django 3.1.4 on 2021-08-09 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0032_auto_20210809_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='consultation_sheet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='consults', to='consultation.consultationsheet', verbose_name='Consultation Sheet'),
        ),
    ]
