# Generated by Django 3.1.4 on 2021-08-09 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0033_auto_20210809_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='consultation_state',
        ),
    ]
