# Generated by Django 3.1.4 on 2021-08-09 20:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0034_remove_consultation_consultation_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='consultation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Consultation Date'),
        ),
    ]
