# Generated by Django 3.1.4 on 2021-08-09 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0035_auto_20210809_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='patient_insurance_plan',
        ),
    ]
