# Generated by Django 3.1.4 on 2021-12-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0036_remove_consultation_patient_insurance_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationsheet',
            name='consultation_date',
            field=models.DateTimeField(verbose_name='Consultation Date'),
        ),
    ]
