# Generated by Django 3.1.4 on 2021-12-20 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0020_auto_20211214_1741'),
        ('consultation', '0037_auto_20211214_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationentrysheet',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultation_entry_sheets', to='invoicing.invoiceheader', verbose_name='Invoice'),
        ),
    ]
