# Generated by Django 3.1.4 on 2021-08-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0038_consultationreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationreport',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
