# Generated by Django 3.1.4 on 2022-02-16 03:51

import consultation.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0038_consultationentrysheet_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('file_name', models.CharField(max_length=250, verbose_name='File Name')),
                ('file', models.FileField(upload_to=consultation.models.consultation_file_storage_path, verbose_name='File')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_text_files', to='consultation.consultation', verbose_name='Consultation')),
                ('consultation_file_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consultation.consultationfiletype')),
            ],
            options={
                'verbose_name': 'Consultation File',
                'verbose_name_plural': 'Consultation Text Files',
            },
        ),
        migrations.RemoveField(
            model_name='consultationsoundfile',
            name='consultation',
        ),
        migrations.RemoveField(
            model_name='consultationsoundfile',
            name='consultation_file_type',
        ),
        migrations.RemoveField(
            model_name='consultationtextfile',
            name='consultation',
        ),
        migrations.RemoveField(
            model_name='consultationtextfile',
            name='consultation_file_type',
        ),
        migrations.RemoveField(
            model_name='consultationvideofile',
            name='consultation',
        ),
        migrations.RemoveField(
            model_name='consultationvideofile',
            name='consultation_file_type',
        ),
        migrations.DeleteModel(
            name='ConsultationImageFile',
        ),
        migrations.DeleteModel(
            name='ConsultationSoundFile',
        ),
        migrations.DeleteModel(
            name='ConsultationTextFile',
        ),
        migrations.DeleteModel(
            name='ConsultationVideoFile',
        ),
    ]
