# Generated by Django 3.1.4 on 2022-02-17 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0039_auto_20220216_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationfile',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_files', to='consultation.consultation', verbose_name='Consultation'),
        ),
        migrations.AlterField(
            model_name='consultationfile',
            name='consultation_file_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultation_files', to='consultation.consultationfiletype', verbose_name='File type'),
        ),
    ]
