# Generated by Django 3.1.4 on 2021-08-13 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0039_auto_20210811_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationreport',
            name='consultation',
        ),
        migrations.RemoveField(
            model_name='consultationreport',
            name='consultation_sheet',
        ),
        migrations.RemoveField(
            model_name='consultationreport',
            name='medical_equipment',
        ),
        migrations.RemoveField(
            model_name='consultationreport',
            name='medical_study',
        ),
        migrations.RemoveField(
            model_name='consultationreport',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='consultationreport',
            name='technician',
        ),
        migrations.RemoveField(
            model_name='consultationreport',
            name='treating_doctor',
        ),
        migrations.AddField(
            model_name='consultation',
            name='consultation_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consults', to='consultation.consultationreport', verbose_name='Consultation Report'),
        ),
    ]
