# Generated by Django 3.1.4 on 2021-09-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0040_auto_20210813_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationreport',
            name='report_title',
            field=models.CharField(default='Titulo Reporte', max_length=200, verbose_name='Report Title'),
            preserve_default=False,
        ),
    ]
