# Generated by Django 3.1.4 on 2021-09-06 19:10

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0026_auto_20210812_0926'),
        ('consultation', '0041_consultationreport_report_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorReportTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('template_text', ckeditor.fields.RichTextField(verbose_name='Template Text')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_reports_templates', to='clinic.doctor', verbose_name='Doctor')),
                ('medical_study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic.medicalstudy', verbose_name='Medical Study')),
            ],
            options={
                'permissions': (('can_undelete', 'Can undelete this object'),),
                'abstract': False,
            },
        ),
    ]
