# Generated by Django 3.1.4 on 2021-09-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0042_doctorreporttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorreporttemplate',
            name='digital_signature',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Digital Signature'),
        ),
    ]
