# Generated by Django 3.1.4 on 2021-09-06 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0043_doctorreporttemplate_digital_signature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorreporttemplate',
            options={'verbose_name': 'Doctor Report Template', 'verbose_name_plural': 'Doctors Reports Templates'},
        ),
    ]
