# Generated by Django 3.1.4 on 2021-09-06 21:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0044_auto_20210906_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationreport',
            name='report',
            field=ckeditor.fields.RichTextField(verbose_name='Report'),
        ),
    ]
