# Generated by Django 3.1.4 on 2021-09-06 22:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0045_auto_20210906_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='notes',
            field=ckeditor.fields.RichTextField(verbose_name='Notes'),
        ),
    ]
