# Generated by Django 3.1.4 on 2021-10-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0046_auto_20210906_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationreport',
            name='add_digital_signature',
            field=models.BooleanField(blank=True, default=False, verbose_name='Add Digital Signature'),
        ),
    ]
