# Generated by Django 3.1.4 on 2021-11-10 14:16

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0026_auto_20210812_0926'),
        ('consultation', '0047_consultationreport_add_digital_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationreport',
            name='audio_report',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='Audio Report'),
        ),
        migrations.AlterField(
            model_name='consultationreport',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultation_reports', to='clinic.doctor', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='consultationreport',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultation_reports', to='clinic.patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='consultationreport',
            name='report',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Report'),
        ),
        migrations.AlterField(
            model_name='consultationreport',
            name='report_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Report Title'),
        ),
    ]
