# Generated by Django 3.1.4 on 2021-12-21 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0049_auto_20211214_1727'),
        ('consultation', '0038_consultationentrysheet_invoice'),
    ]

    operations = [
    ]
