# Generated by Django 3.1.4 on 2022-02-17 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0040_auto_20220217_0942'),
        ('consultation', '0050_merge_20211221_1016'),
    ]

    operations = [
    ]
