# Generated by Django 3.1.4 on 2022-04-28 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0051_merge_20220217_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationreport',
            name='report_title',
            field=models.CharField(max_length=200, null=True, verbose_name='Report Title'),
        ),
    ]
