# Generated by Django 3.1.4 on 2022-04-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0052_auto_20220427_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationstate',
            name='state_code',
            field=models.IntegerField(choices=[(0, 'Filed'), (1, 'Performed'), (2, 'Assigned'), (6, 'Recorded'), (7, 'Copied'), (8, 'Finished'), (3, 'Reported'), (4, 'Prepared'), (5, 'Delivered')], verbose_name='State code'),
        ),
    ]
