# Generated by Django 3.1.4 on 2022-07-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0053_auto_20220428_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationreport',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Mark as Finished'),
        ),
    ]
