# Generated by Django 3.1.4 on 2023-09-08 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0063_customer_sifen_ruc_validated'),
        ('consultation', '0054_consultationreport_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationentrysheet',
            name='credit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultation_entry_sheets', to='invoicing.creditnoteheader', verbose_name='Credit Note'),
        ),
    ]
