# Generated by Django 3.1.4 on 2023-09-14 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0068_auto_20230913_2131'),
        ('consultation', '0055_consultationentrysheet_credit_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationentrysheet',
            name='credit_note',
        ),
        migrations.AddField(
            model_name='consultationentrysheet',
            name='insurance_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insurance_invoice_consultation_entry_sheets', to='invoicing.invoiceheader', verbose_name='Insurance Invoice'),
        ),
    ]
