# Generated by Django 3.1.4 on 2021-06-10 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultation', '0030_consultationentrysheet_total_amount_paid_by_patient'),
        ('base', '0001_initial'),
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationEntrySheetSaleHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('client_name', models.CharField(max_length=150, verbose_name='Client Name')),
                ('client_tax_identification_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Client Tax Identification Number')),
                ('sale_date', models.DateTimeField(verbose_name='Sale Date')),
                ('sale_total', models.FloatField(verbose_name='Sale Total')),
                ('consultation_entry_sheet', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sale_header', to='consultation.consultationentrysheet', verbose_name='Consultation Entry Sheet')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_headers', to='base.currency', verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Consultation Sheet Sale Header',
                'verbose_name_plural': 'Consultation Sheets Sales Headers',
            },
        ),
        migrations.CreateModel(
            name='ConsultationSheetSalePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('amount', models.FloatField(blank=True, default=0, verbose_name='Amount')),
                ('payment_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Payment Date')),
                ('observations', models.TextField(blank=True, default='', null=True, verbose_name='Observations')),
                ('consultation_sheet', models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_payments', to='consultation.consultationsheet', verbose_name='Consultation Sheet')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_payments', to='base.currency', verbose_name='Currency')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoicing.paymentmethod', verbose_name='Payment Method')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_payments', to='sales.consultationentrysheetsaleheader', verbose_name='Sale')),
            ],
            options={
                'verbose_name': 'Consultation Sheet Sale Payment',
                'verbose_name_plural': 'Consultation Sheets Sales Payments',
            },
        ),
        migrations.CreateModel(
            name='ConsultationSheetSaleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('unit_price', models.FloatField(default=0, verbose_name='Unit price')),
                ('total_price', models.FloatField(default=0, verbose_name='Total Price')),
                ('consultation_sheet', models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_details', to='consultation.consultationsheet', verbose_name='Consultation Sheet')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_details', to='base.currency', verbose_name='Currency')),
                ('sale_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_details', to='sales.consultationentrysheetsaleheader', verbose_name='Sale Header')),
            ],
            options={
                'verbose_name': 'Consultation Sheet Sale Detail',
                'verbose_name_plural': 'Consultation Sheets Sales Details',
            },
        ),
    ]
