# Generated by Django 3.1.4 on 2021-06-10 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationsheetsalepayment',
            name='payment_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Payment Date'),
        ),
    ]
