# Generated by Django 3.1.4 on 2021-07-08 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0030_consultationentrysheet_total_amount_paid_by_patient'),
        ('sales', '0003_auto_20210610_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationentrysheetsaleheader',
            name='consultation_entry_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_header', to='consultation.consultationentrysheet', verbose_name='Consultation Entry Sheet'),
        ),
    ]
